#!/bin/bash
INPUT_FILE="./data/problem0.fna.indexed"
WRITE_MAWS="1"
OUTPUT_FILE="./data/problem0.fna.maws.compressed"
N_THREADS="4"


MIN_LENGTH="2"
MAX_LENGTH="100000"
MIN_HISTOGRAM_LENGTH="0"
MAX_HISTOGRAM_LENGTH="0"


COMPUTE_SCORES="0"
SELECT_SCORE="0"
SCORE_THRESHOLD="0"


COMPRESS_OUTPUT="1"


./run_MAWs_single ${INPUT_FILE} ${N_THREADS} \
	${MIN_LENGTH} ${MAX_LENGTH} ${MIN_HISTOGRAM_LENGTH} ${MAX_HISTOGRAM_LENGTH} \
	${COMPUTE_SCORES} ${SELECT_SCORE} ${SCORE_THRESHOLD} \
	${WRITE_MAWS} ${OUTPUT_FILE} ${COMPRESS_OUTPUT}
