#/bin/bash
INPUT_FILE="../data/HS22.fasta.indexed"
N_THREADS="2"

MIN_LENGTH="0"
MAX_LENGTH="1000000000"
MIN_HISTOGRAM_LENGTH="0"
MAX_HISTOGRAM_LENGTH="0"

COMPUTE_SCORES="0"
SELECT_SCORE="0"
SCORE_THRESHOLD="0"

WRITE_MAWS="0"
OUTPUT_FILE="../data/HS22.fasta.maws.basic"
COMPRESS_OUTPUT="0"


./run_MAWs_single ${INPUT_FILE} ${N_THREADS} \
	${MIN_LENGTH} ${MAX_LENGTH} ${MIN_HISTOGRAM_LENGTH} ${MAX_HISTOGRAM_LENGTH} \
	${COMPUTE_SCORES} ${SELECT_SCORE} ${SCORE_THRESHOLD} \
	${WRITE_MAWS} ${OUTPUT_FILE} ${COMPRESS_OUTPUT}
