#/bin/bash
INPUT_FILE="../data/HS22.fasta"
APPEND_RC="0"
WRITE_MAWS="1"
OUTPUT_FILE="../data/HS22.fasta.maws.filter"

# Statistics
MIN_HISTOGRAM_LENGTH="2"
MAX_HISTOGRAM_LENGTH="1000"
COMPUTE_SCORES="1"

# Filtering by length
MIN_LENGTH="2"

# Filtering by score
SELECT_SCORE="3"
SCORE_THRESHOLD="2"

# Compression
COMPRESS_OUTPUT="0"

# Max length of a MAW
MAX_LENGTH=100000;


./run_MAWs_single ${INPUT_FILE} ${APPEND_RC} ${MIN_LENGTH} ${MIN_HISTOGRAM_LENGTH} ${MAX_HISTOGRAM_LENGTH} ${WRITE_MAWS} ${COMPUTE_SCORES} ${SELECT_SCORE} ${SCORE_THRESHOLD} ${COMPRESS_OUTPUT} ${OUTPUT_FILE} ${MAX_LENGTH}