#/bin/bash
INPUT_FILE="./data/HS22.fasta"
APPEND_RC="0"
WRITE_MAWS="0"
OUTPUT_FILE="./data/HS22.fasta.maws.basic"

# Statistics
MIN_HISTOGRAM_LENGTH="0"
MAX_HISTOGRAM_LENGTH="0"
COMPUTE_SCORES="0"

# Filtering by length
MIN_LENGTH="2"

# Filtering by score
SELECT_SCORE="0"
SCORE_THRESHOLD="0"

# Compression
COMPRESS_OUTPUT="0"

# Max length of a MAW
MAX_LENGTH=9;


./run_MAWs_single ${INPUT_FILE} ${APPEND_RC} ${MIN_LENGTH} ${MIN_HISTOGRAM_LENGTH} ${MAX_HISTOGRAM_LENGTH} ${WRITE_MAWS} ${COMPUTE_SCORES} ${SELECT_SCORE} ${SCORE_THRESHOLD} ${COMPRESS_OUTPUT} ${OUTPUT_FILE} ${MAX_LENGTH}