#!/bin/bash
INPUT_FILE="./data/problem0.fna.indexed"
WRITE_MAWS="1"
OUTPUT_FILE="./data/problem0.fna.maws.filter"
N_THREADS="1"


MIN_LENGTH="2"
MAX_LENGTH="100000"
MIN_HISTOGRAM_LENGTH="2"
MAX_HISTOGRAM_LENGTH="1000"


COMPUTE_SCORES="1"
SELECT_SCORE="3"
SCORE_THRESHOLD="2"


COMPRESS_OUTPUT="0"


./run_MAWs_single ${INPUT_FILE} ${N_THREADS} \
	${MIN_LENGTH} ${MAX_LENGTH} ${MIN_HISTOGRAM_LENGTH} ${MAX_HISTOGRAM_LENGTH} \
	${COMPUTE_SCORES} ${SELECT_SCORE} ${SCORE_THRESHOLD} \
	${WRITE_MAWS} ${OUTPUT_FILE} ${COMPRESS_OUTPUT}
