#ifndef MAWs_single_h
#define MAWs_single_h


#include "../io/io.h"
#include "../iterator/SLT_single_string.h"


/**  
 * @param minLength (>=2) considers only MAWs of length at least $minLength$;
 * @param writeMAWs 0 iff MAWs should not be written to the output; otherwise, MAWs are  
 * appended to file $filePath$;
 * @param computeScore if nonzero, assigns to each MAW $W$ of length $k$ an estimate of  
 * the probability of observing $W$, if the text is generated by a Markov chain of order  
 * at most $k-2$;
 * @return the number of MAWs found.
 */
unsigned int find_MAWs_single(Basic_BWT_t *BBWT, unsigned int textLength, unsigned int minLength, unsigned char writeMAWs, unsigned char computeScore, char *filePath);


#endif